title: Jekyll Admin Demo
email: d@derekadair.com.com
description: Functional jekyll admin
baseurl: ''
url: 'http://jekyll.sandbox.derekadair.com'
host: 0.0.0.0
twitter_username: derleek
github_username: derek-adair
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-sitemap
